USE [master]
GO

/****** Object:  Database [iAuditor]    Script Date: 2/26/2019 11:40:17 AM ******/
CREATE DATABASE [iAuditor]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'iAuditor', FILENAME = N'D:\SQLData\iAuditor.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 32768KB )
 LOG ON 
( NAME = N'iAuditor_log', FILENAME = N'D:\SQLLogs\iAuditor_log.ldf' , SIZE = 1024KB , MAXSIZE = 5242880KB , FILEGROWTH = 32768KB )
GO

ALTER DATABASE [iAuditor] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [iAuditor].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [iAuditor] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [iAuditor] SET ANSI_NULLS ON 
GO

ALTER DATABASE [iAuditor] SET ANSI_PADDING ON 
GO

ALTER DATABASE [iAuditor] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [iAuditor] SET ARITHABORT ON 
GO

ALTER DATABASE [iAuditor] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [iAuditor] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [iAuditor] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [iAuditor] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [iAuditor] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [iAuditor] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [iAuditor] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [iAuditor] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [iAuditor] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [iAuditor] SET  DISABLE_BROKER 
GO

ALTER DATABASE [iAuditor] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [iAuditor] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [iAuditor] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [iAuditor] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [iAuditor] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [iAuditor] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [iAuditor] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [iAuditor] SET RECOVERY FULL 
GO

ALTER DATABASE [iAuditor] SET  MULTI_USER 
GO

ALTER DATABASE [iAuditor] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [iAuditor] SET DB_CHAINING OFF 
GO

ALTER DATABASE [iAuditor] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [iAuditor] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [iAuditor] SET  READ_WRITE 
GO
